/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pico.Placa_Interfaz;
import java.util.Date;
import pico.Placa_Funcionalidad.PicoPlaca_Funciones;



public class MainPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public MainPrincipal() {
        initComponents();
        setLocationRelativeTo(this); //we show the interface in the middle of the display
        this.Label_error1.setVisible(false); //at first the error messages will be disabled
        this.Label_error2.setVisible(false);
        Date now = new Date();
        this.Calendar.setDate(now); // we set the calendary with the actual date
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_title = new javax.swing.JLabel();
        Label_plateinformation = new javax.swing.JLabel();
        Label_error1 = new javax.swing.JLabel();
        TextField_plate = new javax.swing.JTextField();
        Label_error2 = new javax.swing.JLabel();
        Label_calendarinformation = new javax.swing.JLabel();
        Calendar = new com.toedter.calendar.JDateChooser();
        Label_sheduleinformation = new javax.swing.JLabel();
        ComboBox_schedule = new javax.swing.JComboBox<>();
        Button_verify = new javax.swing.JButton();
        Label_results = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_title.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Label_title.setForeground(new java.awt.Color(0, 204, 204));
        Label_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_title.setText("VALIDADOR DE PICO Y PLACA");

        Label_plateinformation.setText("Ingrese el número de placa. Ejemplo PBD3219");

        Label_error1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_error1.setForeground(new java.awt.Color(255, 0, 0));
        Label_error1.setText("Numero de Placa Incorrecto!");

        TextField_plate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_plateActionPerformed(evt);
            }
        });

        Label_error2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label_error2.setForeground(new java.awt.Color(255, 0, 0));
        Label_error2.setText("*");

        Label_calendarinformation.setText("Seleccione una fecha");

        Label_sheduleinformation.setText("Seleccione un horario");

        ComboBox_schedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00h00-06h59", "07h00-09h30", "09h31-15h59", "16h00-19h30", "19h31-23h59" }));

        Button_verify.setBackground(new java.awt.Color(255, 204, 0));
        Button_verify.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Button_verify.setForeground(new java.awt.Color(102, 102, 102));
        Button_verify.setText("VERIFICAR");
        Button_verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_verifyActionPerformed(evt);
            }
        });

        Label_results.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_results.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_error2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_calendarinformation))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_sheduleinformation)
                                    .addComponent(ComboBox_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Label_plateinformation))
                        .addGap(0, 85, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField_plate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_error1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_title)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(Button_verify))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_results, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_plateinformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_plate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_error1)
                            .addComponent(Label_error2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_sheduleinformation)
                            .addComponent(Label_calendarinformation, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboBox_schedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Button_verify)
                .addGap(18, 18, 18)
                .addComponent(Label_results, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_verifyActionPerformed
        // TODO add your handling code here:
        PicoPlaca_Funciones sistema = new PicoPlaca_Funciones(); // We initialize the class to run the functions created in PicoYPlacaSystem
        sistema.plateValidator(this.TextField_plate, this.Label_error1, this.Label_error2, this.Label_results);
        sistema.verificacionDeRestriccion(this.Calendar, this.ComboBox_schedule, this.TextField_plate, this.Label_results, this.Label_error1, this.Label_error2);
  
    }//GEN-LAST:event_Button_verifyActionPerformed

    private void TextField_plateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_plateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_plateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_verify;
    private com.toedter.calendar.JDateChooser Calendar;
    private javax.swing.JComboBox<String> ComboBox_schedule;
    private javax.swing.JLabel Label_calendarinformation;
    private javax.swing.JLabel Label_error1;
    private javax.swing.JLabel Label_error2;
    private javax.swing.JLabel Label_plateinformation;
    private javax.swing.JLabel Label_results;
    private javax.swing.JLabel Label_sheduleinformation;
    private javax.swing.JLabel Label_title;
    private javax.swing.JTextField TextField_plate;
    // End of variables declaration//GEN-END:variables
}
